/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001a42",
        "primary-container": "#006fef",
        "outline": "#727786",
        "tertiary-fixed": "#ffdbcd",
        "primary": "#0058bf",
        "inverse-primary": "#aec6ff",
        "surface-container-low": "#f1f3ff",
        "surface-bright": "#f9f9ff",
        "outline-variant": "#c1c6d7",
        "secondary": "#8f4e00",
        "on-surface-variant": "#414755",
        "surface-tint": "#005ac4",
        "on-background": "#181b23",
        "on-secondary-fixed": "#2e1500",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e0e2ed",
        "secondary-fixed-dim": "#ffb77a",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e6e7f3",
        "secondary-container": "#fe9832",
        "surface-variant": "#e0e2ed",
        "on-primary-fixed-variant": "#004396",
        "tertiary-container": "#c84d00",
        "primary-fixed": "#d8e2ff",
        "on-error": "#ffffff",
        "surface": "#f9f9ff",
        "tertiary": "#9f3c00",
        "on-surface": "#181b23",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "inverse-surface": "#2d3039",
        "on-tertiary-container": "#fffbff",
        "on-primary-container": "#fefcff",
        "primary-fixed-dim": "#aec6ff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#360f00",
        "surface-container": "#ecedf9",
        "on-secondary-container": "#683700",
        "tertiary-fixed-dim": "#ffb596",
        "background": "#f9f9ff",
        "inverse-on-surface": "#eef0fc",
        "surface-dim": "#d8d9e5",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffdcc2",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#6d3a00",
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
      },
      spacing: {
        sm: "16px",
        gutter: "20px",
        lg: "48px",
        "container-max": "1280px",
        xs: "8px",
        base: "4px",
        md: "24px",
        xl: "80px",
      },
    },
  },
  plugins: [],
};
